#ifndef PYTHON_TOKENS_H
#define PYTHON_TOKENS_H
#include <sys/_types/_null.h>

/* Python Tokens and Data */
#define numPythonKeywords 30
#define numPythonOperators 21
#define numPythonDelimiters 25
#define numSpecialPythonTokens 4
#define numUnusedPythonTokens 3

typedef enum  {
  /* Keywords */
  PYTOK_AND,
  PYTOK_AS,
  PYTOK_ASSERT,
  PYTOK_BREAK,
  PYTOK_CLASS,
  PYTOK_DEF,
  PYTOK_DEL,
  PYTOK_ELIF,
  PYTOK_ELSE,
  PYTOK_EXCEPT,
  PYTOK_EXEC,
  PYTOK_FINALLY,
  PYTOK_FOR,
  PYTOK_FROM,
  PYTOK_GLOBAL,
  PYTOK_IF,
  PYTOK_IMPORT,
  PYTOK_IN,
  PYTOK_IS,
  PYTOK_LAMBDA,
  PYTOK_NOT,
  PYTOK_OR,
  PYTOK_PASS,
  PYTOK_PRINT,
  PYTOK_RAISE,
  PYTOK_RETURN,
  PYTOK_TRY,
  PYTOK_WHILE,
  PYTOK_WITH,
  PYTOK_YIELD,

  /* Operators */
  PYTOK_PLUS,
  PYTOK_MINUS,
  PYTOK_MULTIPLY,
  PYTOK_POWER,
  PYTOK_DIVIDE,
  PYTOK_FLOORDIVIDE,
  PYTOK_MODULO,
  PYTOK_MATRIXMULTIPLY,
  PYTOK_LEFTSHIFT,
  PYTOK_RIGHTSHIFT,
  PYTOK_BITWISEAND,
  PYTOK_BITWISEOR,
  PYTOK_BITWISEXOR,
  PYTOK_BITWISENOT,
  PYTOK_WALRUS,

  /* Delimiters */
  PYTOK_LEFTPARENTHESIS,
  PYTOK_RIGHTPARENTHESIS,
  PYTOK_LEFTSQUAREBRACKET,
  PYTOK_RIGHTSQUAREBRACKET,
  PYTOK_LEFTCURLYBRACE,
  PYTOK_RIGHTCURLYBRACE,
  PYTOK_COMMA,
  PYTOK_COLON,
  PYTOK_DOT,
  PYTOK_SEMICOLON,
  PYTOK_AT,
  PYTOK_ASSIGNMENT,
  PYTOK_PLUSEQUAL,
  PYTOK_MINUSEQUAL,
  PYTOK_MULTIPLYEQUAL,
  PYTOK_DIVIDEEQUAL,
  PYTOK_FLOORDIVIDEEQUAL,
  PYTOK_MODULOEQUAL,
  PYTOK_MATRIXMULTIPLYEQUAL,
  PYTOK_BITWISEANDEQUAL,
  PYTOK_BITWISEOREQUAL,
  PYTOK_BITWISEXOREQUAL,
  PYTOK_RIGHTSHIFTEQUAL,
  PYTOK_LEFTSHIFTEQUAL,
  PYTOK_POWEREQUAL,

  /* Special Tokens */
  PYTOK_SINGLEQUOTE,
  PYTOK_DOUBLEQUOTE,
  PYTOK_HASH,
  PYTOK_BACKSLASH,

  /* Unused Tokens */
  PYTOK_DOLLAR,
  PYTOK_QUESTIONMARK,
  PYTOK_BACKTICK,

  /* Unknown */
  UNKNOWN,

  /* Identifiers */
  PYTOK_IDENTIFIER
}PythonTokenType;

#endif /* PYTHON_TOKENS_H */
