#ifndef PYTHON_TOKENS_H
#define PYTHON_TOKENS_H
#include <sys/_types/_null.h>

/* Python Tokens and Data */
#define numPythonKeywords 30
#define numPythonOperators 21
#define numPythonDelimiters 25
#define numSpecialPythonTokens 4
#define numUnusedPythonTokens 3

typedef enum  {
  /* Keywords */
  PY_KEYWORD_AND,
  PY_KEYWORD_AS,
  PY_KEYWORD_ASSERT,
  PY_KEYWORD_BREAK,
  PY_KEYWORD_CLASS,
  PY_KEYWORD_DEF,
  PY_KEYWORD_DEL,
  PY_KEYWORD_ELIF,
  PY_KEYWORD_ELSE,
  PY_KEYWORD_EXCEPT,
  PY_KEYWORD_EXEC,
  PY_KEYWORD_FINALLY,
  PY_KEYWORD_FOR,
  PY_KEYWORD_FROM,
  PY_KEYWORD_GLOBAL,
  PY_KEYWORD_IF,
  PY_KEYWORD_IMPORT,
  PY_KEYWORD_IN,
  PY_KEYWORD_IS,
  PY_KEYWORD_LAMBDA,
  PY_KEYWORD_NOT,
  PY_KEYWORD_OR,
  PY_KEYWORD_PASS,
  PY_KEYWORD_PRINT,
  PY_KEYWORD_RAISE,
  PY_KEYWORD_RETURN,
  PY_KEYWORD_TRY,
  PY_KEYWORD_WHILE,
  PY_KEYWORD_WITH,
  PY_KEYWORD_YIELD,

  /* Operators */
  PY_OP_PLUS,
  PY_OP_MINUS,
  PY_OP_MULTIPLY,
  PY_OP_POWER,
  PY_OP_DIVIDE,
  PY_OP_FLOORDIVIDE,
  PY_OP_MODULO,
  PY_OP_MATRIXMULTIPLY,
  PY_OP_LEFTSHIFT,
  PY_OP_RIGHTSHIFT,
  PY_OP_BITWISEAND,
  PY_OP_BITWISEOR,
  PY_OP_BITWISEXOR,
  PY_OP_BITWISENOT,
  PY_OP_WALRUS,


  /* Delimiters */
  PY_DELIM_LEFTPARENTHESIS,
  PY_DELIM_RIGHTPARENTHESIS,
  PY_DELIM_LEFTSQUAREBRACKET,
  PY_DELIM_RIGHTSQUAREBRACKET,
  PY_DELIM_LEFTCURLYBRACE,
  PY_DELIM_RIGHTCURLYBRACE,
  PY_DELIM_COMMA,
  PY_DELIM_COLON,
  PY_DELIM_DOT,
  PY_DELIM_SEMICOLON,
  PY_DELIM_AT,
  PY_DELIM_ASSIGNMENT,
  PY_DELIM_PLUSEQUAL,
  PY_DELIM_MINUSEQUAL,
  PY_DELIM_MULTIPLYEQUAL,
  PY_DELIM_DIVIDEEQUAL,
  PY_DELIM_FLOORDIVIDEEQUAL,
  PY_DELIM_MODULOEQUAL,
  PY_DELIM_MATRIXMULTIPLYEQUAL,
  PY_DELIM_BITWISEANDEQUAL,
  PY_DELIM_BITWISEOREQUAL,
  PY_DELIM_BITWISEXOREQUAL,
  PY_DELIM_RIGHTSHIFTEQUAL,
  PY_DELIM_LEFTSHIFTEQUAL,
  PY_DELIM_POWEREQUAL,

  /* Special Tokens */
  PY_SPEC_SINGLEQUOTE,
  PY_SPEC_DOUBLEQUOTE,
  PY_SPEC_HASH,
  PY_SPEC_BACKSLASH,

  /* Unused Tokens */
  PY_UNUSED_DOLLAR,
  PY_UNUSED_QUESTIONMARK,
  PY_UNUSED_BACKTICK,

  /* Unknown */
  UNKNOWN
}PythonTokenType;

#endif /* PYTHON_TOKENS_H */
