/*
TODO: implement fsm for different datatypes
*/

typedef enum {
  TOKEN_KEYWORD_INT,
  TOKEN_KEYWORD_FLOAT,
  TOKEN_KEYWORD_CHAR,
  TOKEN_KEYWORD_CHAR_PTR,
  TOKEN_KEYWORD_WHILE,
  TOKEN_KEYWORD_FOR,
  TOKEN_KEYWORD_IF,
  TOKEN_KEYWORD_RETURN,
  TOKEN_OP_ADD,
  TOKEN_OP_SUBTRACT,
  TOKEN_OP_MULTIPLY,
  TOKEN_OP_DIVIDE,
  TOKEN_OP_EQ,
  TOKEN_OP_DOUBLE_EQ,
  TOKEN_PUNCT_LEFT_PAREN,
  TOKEN_PUNCT_RIGHT_PAREN,
  TOKEN_PUNCT_END_OF_LINE,
  TOKEN_OP_SINGLE_AND,
  TOKEN_OP_DOUBLE_AND,
  TOKEN_IDENTIFIER,
  TOKEN_LITERAL_INT,
  TOKEN_LITERAL_FLOAT,
  TOKEN_LITERAL_CHAR,
  TOKEN_LITERAL_STRING,
  TOKEN_BLOCK_COMMENT_START,
  TOKEN_BLOCK_COMMENT_END,
  TOKEN_UNKNOWN
} TokenType;

int test(void) { return 0; }
